monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                max_files: 7  # Keep dev logs for 7 days (shorter retention for development)
                channels: ["!event"]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            # Main handler - daily rotating logs with 15-day retention
            main:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: info
                max_files: 15  # Keep logs for 15 days
                channels: ["!event"]
                formatter: monolog.formatter.json

            # Critical errors handler - uses fingers_crossed for buffering
            critical:
                type: fingers_crossed
                action_level: error
                handler: critical_nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
                channels: ["!event"]

            critical_nested:
                type: rotating_file
                path: "%kernel.logs_dir%/critical.log"
                level: error
                max_files: 15  # Keep critical logs for 15 days
                formatter: monolog.formatter.json

            # Console handler for CLI commands
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]

            # Deprecation warnings - daily rotation
            deprecation:
                type: rotating_file
                channels: [deprecation]
                path: "%kernel.logs_dir%/deprecation.log"
                level: info
                max_files: 15  # Keep deprecation logs for 15 days
                formatter: monolog.formatter.json

            # Application errors to stderr (for Docker/systemd)
            stderr:
                type: stream
                path: php://stderr
                level: error
                formatter: monolog.formatter.json
                channels: ["!event", "!doctrine", "!deprecation"]
